<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Presentation\Windows\Windows.csproj" />
    <ProjectReference Include="..\..\Presentation\Timeline\Timeline.csproj" />
    <ProjectReference Include="..\..\Presentation\Styling\Styling.csproj" />
    <ProjectReference Include="..\..\Domain\Model\Model.csproj" />
  </ItemGroup>
</Project>
