#!/usr/bin/env python3
"""Write researched Python and TypeScript interview packs under Resources/practice/."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "Resources" / "practice"


def item(qid: str, pack: str, group: str, topic: str, title: str, text: str, answer: str, hints: list[str]) -> dict:
    return {
        "id": qid,
        "packId": pack,
        "groupId": group,
        "topicId": topic,
        "topicTitle": title,
        "text": text,
        "hints": hints,
        "rubric": answer,
        "answer": answer,
    }


PYTHON: list[tuple] = [
    ("list-tuple", "What is the difference between a list and a tuple?",
     "A list is mutable; a tuple is not. Tuples are a bit smaller and faster, and a tuple of hashable items can be a dict key. Use a list when the sequence will grow or change; use a tuple for fixed records and return values. A one-element tuple needs a trailing comma: (1,).",
     ["List is mutable.", "Tuple can be a dict key.", "(1,) is a one-element tuple."], "collections"),
    ("eq-is", "What is the difference between == and is in Python?",
     "== calls __eq__ and compares values. is compares object identity (the same object in memory). None checks should use is; interned small ints and interned strings can make is look like == and mislead you.",
     ["== is value.", "is is identity.", "Use is for None."], "data-model"),
    ("dict-key-list", "Why can a list not be used as a dictionary key?",
     "Dict keys must be hashable. A list is mutable, so its contents can change after it is inserted, which would break the hash table. A tuple of hashable items is fine.",
     ["Keys must be hashable.", "Lists are mutable.", "Tuples of immutables work."], "collections"),
    ("args-kwargs", "What are *args and **kwargs?",
     "*args collects extra positional arguments into a tuple. **kwargs collects extra keyword arguments into a dict. In a call, * unpacks a sequence and ** unpacks a mapping. Use them for wrappers and forwarders, not to hide a messy API.",
     ["*args is a tuple.", "**kwargs is a dict.", "Unpack with * and **."], "functions"),
    ("decorators", "What is a Python decorator, and when does it run?",
     "A decorator is a callable that takes a function and returns a wrapped function. The @ syntax runs at import/definition time, not at call time. Use functools.wraps so __name__ and help stay on the original.",
     ["It wraps a function.", "It runs at definition time.", "Use functools.wraps."], "functions"),
    ("late-binding", "What is the late-binding closure pitfall in a loop?",
     "A nested function looks up free variables at call time, not at definition. lambdas in a for-loop all see the last value of the loop variable. Bind it as a default: lambda i=i: i.",
     ["Lookup is at call time.", "Loop vars all share the last value.", "Bind with a default arg."], "functions"),
    ("mutable-default", "Why is a mutable default argument a bug?",
     "Default values are evaluated once, when the function is defined. A default list or dict is shared across calls, so appends leak between invocations. Use None and create the list inside the function.",
     ["Defaults evaluate once.", "The list is shared.", "Use None as the default."], "functions"),
    ("shallow-deep", "What is the difference between a shallow copy and a deep copy?",
     "copy.copy / slicing copies the outer container only; nested objects are shared. copy.deepcopy walks the graph and clones nested objects. Shallow is enough for a list of ints; nested dicts of lists need deep copy.",
     ["Shallow shares nested objects.", "Deep clone walks the graph.", "copy.deepcopy for nested mutables."], "data-model"),
    ("legb", "What is the LEGB rule?",
     "Name lookup order is Local, Enclosing, Global, Built-in. Assignment without global/nonlocal creates a local. Use global to write a module name, nonlocal to write an enclosing function's name.",
     ["Local, Enclosing, Global, Built-in.", "Assignment makes a local.", "nonlocal writes the outer function."], "data-model"),
    ("new-init", "What is the difference between __new__ and __init__?",
     "__new__ is a static constructor that allocates and returns the instance (or another object). __init__ initializes that instance. Immutable types and metaclasses customize __new__; day-to-day classes use __init__.",
     ["__new__ allocates.", "__init__ initializes.", "Immutables override __new__."], "oop"),
    ("mro", "What is the method resolution order (MRO)?",
     "MRO is the linear order Python uses to find attributes on a class, C3 linearization. See Class.__mro__ or Class.mro(). super() follows that order, which is how cooperative multiple inheritance works.",
     ["C3 linearization.", "Class.__mro__ shows it.", "super() walks the MRO."], "oop"),
    ("super", "How does super() work in Python 3?",
     "super() returns a proxy that continues the MRO after the current class. In a cooperative diamond, every override should call super() so each class runs once. Do not hard-code the parent class name.",
     ["It follows the MRO.", "Call it in every override.", "Do not hard-code the parent."], "oop"),
    ("context-manager", "What is a context manager?",
     "An object with __enter__ and __exit__. with calls enter, then exit in a finally — even on exception. Use it for locks, files, and sessions so cleanup cannot be skipped.",
     ["__enter__ and __exit__.", "with always runs exit.", "Files, locks, sessions."], "stdlib"),
    ("classmethod-static", "What is the difference between @classmethod and @staticmethod?",
     "@classmethod receives the class as cls — use it for alternate constructors. @staticmethod is a namespaced function with no cls/self. Prefer classmethod when you need the actual subclass.",
     ["classmethod gets cls.", "staticmethod gets nothing.", "Use classmethod for factories."], "oop"),
    ("property", "What does @property do?",
     "It turns a method into an attribute: obj.x calls the getter. Pair with .setter to validate writes. It is a descriptor, so it works on the class, not a per-instance function.",
     ["Getter as an attribute.", "Optional setter.", "It is a descriptor."], "oop"),
    ("slots", "What is __slots__?",
     "__slots__ lists allowed attribute names and skips the per-instance __dict__. That saves memory on many small objects. You cannot assign undeclared attributes unless you also include '__dict__'.",
     ["No per-instance __dict__.", "Saves memory.", "Unknown attrs raise."], "oop"),
    ("descriptor", "What is a descriptor?",
     "An object with __get__/__set__/__delete__ stored on the class. Functions, properties, and classmethods are descriptors. Data descriptors (with __set__) override instance dict entries.",
     ["__get__/__set__ on the class.", "property is a descriptor.", "Data descriptors win over the instance dict."], "oop"),
    ("metaclass", "What is a metaclass?",
     "The class of a class. type is the default. A metaclass's __new__/__init__ run when the class body finishes — for ORMs, ABCs, and registries. Most code should not write one.",
     ["A class's class.", "type is the default.", "Runs at class creation."], "oop"),
    ("eafp", "What is EAFP versus LBYL?",
     "EAFP: try the operation, catch the exception (Pythonic). LBYL: check first (if key in d). EAFP avoids races between check and use; LBYL is clearer when the miss is common and cheap.",
     ["EAFP is try/except.", "LBYL is if-check.", "EAFP avoids TOCTOU races."], "style"),
    ("duck-typing", "What is duck typing?",
     "If it quacks like a duck, it is a duck: you care about methods, not a nominal type. File-like objects and iterators work this way. Protocols/ABCs document the shape when you need a name.",
     ["Behavior over type name.", "File-like objects.", "Protocols name the shape."], "style"),
    ("module-package", "What is the difference between a module and a package?",
     "A module is a .py file (or C extension). A package is a directory with __init__.py (or a namespace package without it). import pkg.mod loads the package then the module.",
     ["Module is a file.", "Package is a directory.", "__init__.py is classic."], "packaging"),
    ("name-main", "What does if __name__ == \"__main__\" do?",
     "__name__ is \"__main__\" only when the file is the entry script. Importing the file as a module does not run that block. Put CLI and demo code there so imports stay side-effect light.",
     ["True for the entry script.", "Imports skip the block.", "Keep import side effects small."], "packaging"),
    ("venv", "Why use a virtual environment?",
     "It isolates project dependencies from the system Python and from other projects. pip install then cannot break OS tools. Recreate it from requirements.txt or a lockfile.",
     ["Isolates dependencies.", "Protects system Python.", "Pin with a lockfile."], "packaging"),
    ("bytes-str", "What is the difference between bytes and str?",
     "str is Unicode text. bytes is raw 8-bit data. Decode bytes to str with an encoding (utf-8); encode the other way. Mixing them is a TypeError in Python 3.",
     ["str is text.", "bytes is binary.", "Decode/encode with utf-8."], "data-model"),
    ("gc", "How does garbage collection work in CPython?",
     "CPython uses reference counting plus a cyclic GC. When a refcount hits zero the object is freed immediately. Cycles (A points at B points at A) need the generational collector.",
     ["Refcount first.", "Cycles need the GC.", "gc.collect() runs it."], "memory"),
    ("refcount", "What is a reference count?",
     "Each object tracks how many pointers refer to it. Names, containers, and call stacks all increment it. del or leaving scope decrements. sys.getrefcount is one higher because the argument itself is a ref.",
     ["Count of live pointers.", "Zero frees the object.", "getrefcount includes the argument."], "memory"),
    ("pass-assignment", "Does Python pass by value or by reference?",
     "Neither slogan is right: it passes object references by assignment. Rebinding a parameter does not rebind the caller's name. Mutating a mutable object in place is visible to the caller.",
     ["Pass object references.", "Rebind is local.", "In-place mutate is shared."], "data-model"),
    ("append-extend", "What is the difference between list.append and list.extend?",
     "append adds one object as a single element (even if it is a list). extend iterates its argument and adds each item. += on a list is extend.",
     ["append one object.", "extend iterates.", "+= is extend."], "collections"),
    ("set", "When do you use a set?",
     "For unique membership tests in average O(1). Items must be hashable. Use for dedup, difference, and intersection. Order is insertion order in modern CPython but do not rely on it for API contracts unless you mean that.",
     ["Unique, O(1) lookup.", "Items must be hashable.", "Dedup and set algebra."], "collections"),
    ("frozenset", "What is a frozenset?",
     "An immutable set. It is hashable, so it can be a dict key or a member of another set. Use it when a set of tags must itself be a key.",
     ["Immutable set.", "Hashable.", "Set-as-key."], "collections"),
    ("genexp", "What is a generator expression?",
     "(x*x for x in xs) is lazy: it yields one value at a time. sum(x*x for x in xs) never builds the list. Parentheses, not square brackets — square brackets are a list comprehension and allocate everything.",
     ["Lazy, one value at a time.", "Parentheses, not [].", "Use inside sum/any/all."], "iterators"),
    ("yield-from", "What does yield from do?",
     "It delegates to a subgenerator: yields its values, forwards .send/.throw, and returns the subgenerator's StopIteration value. It flattens nested generators without a manual loop.",
     ["Delegates to a subgenerator.", "Forwards send/throw.", "Returns the inner value."], "iterators"),
    ("iterator-protocol", "What is the iterator protocol?",
     "An iterable's __iter__ returns an iterator. An iterator has __iter__ (returns self) and __next__, which raises StopIteration when done. for x in xs calls iter then next until StopIteration.",
     ["__iter__ and __next__.", "StopIteration ends it.", "for uses that loop."], "iterators"),
    ("for-else", "What does else on a for loop mean?",
     "The else runs if the loop did not break. Use it for \"search failed\" after a for with a break on success. It is not \"run when empty.\"",
     ["Runs if no break.", "Good for search-failed.", "Not \"when empty.\""], "syntax"),
    ("try-else", "What does else on try mean?",
     "else runs when no exception was raised in try. Use it for code that should not catch exceptions from the success path. finally still runs after else.",
     ["No exception in try.", "Keep success-path exceptions out of except.", "finally still runs."], "syntax"),
    ("finally", "Is finally guaranteed to run?",
     "Yes for normal exceptions, return, and break — with a catch: os._exit, a crash, or a kill -9 skip it. Do not use finally for locks if you also return inside try without care; the with statement is clearer.",
     ["Runs on except and return.", "Not on process kill.", "Prefer with for resources."], "syntax"),
    ("exception-base", "What is the difference between Exception and BaseException?",
     "Exception is the user-catchable hierarchy. BaseException also includes SystemExit, KeyboardInterrupt, and GeneratorExit. except Exception does not swallow Ctrl-C; except: or except BaseException does.",
     ["Exception is user errors.", "KeyboardInterrupt is BaseException.", "Do not bare-except."], "syntax"),
    ("lru-cache", "What is functools.lru_cache?",
     "A memoizing decorator with a max size and LRU eviction. Arguments must be hashable. Use cache_info() in tests. For unbound growth use cache; for identity by id it is the wrong tool.",
     ["Memoize with LRU.", "Args must be hashable.", "cache_info() for hits."], "stdlib"),
    ("wraps", "Why does a decorator need functools.wraps?",
     "Without wraps, the wrapper's __name__, __doc__, and signature hide the original. wraps copies those attributes so help(), logging, and tests still see the wrapped function.",
     ["Keeps __name__ and __doc__.", "Help and logs stay honest.", "Put it on the wrapper."], "functions"),
    ("partial", "What is functools.partial?",
     "It freezes some arguments of a callable and returns a new callable. Use it instead of a lambda when you only want to bind args. The original function is on .func.",
     ["Binds some arguments.", "Better than a tiny lambda.", ".func is the original."], "stdlib"),
    ("dataclass-namedtuple", "When do you use a dataclass versus a namedtuple?",
     "namedtuple is an immutable tuple with names — cheap, unpackable, hashable. dataclass is a generated class: optional frozen, defaults, and methods. Prefer dataclass unless you need tuple unpacking or a tiny record.",
     ["namedtuple is a tuple.", "dataclass is a class.", "frozen=True for hashability."], "oop"),
    ("hash-eq", "Why must __hash__ and __eq__ stay consistent?",
     "If a == b then hash(a) must equal hash(b), or dict/set lookup breaks. Mutable objects that define __eq__ should set __hash__ = None. Frozen dataclasses get both generated together.",
     ["Equal objects equal hashes.", "Mutables: __hash__ = None.", "Frozen dataclass is consistent."], "data-model"),
    ("counter", "What is collections.Counter for?",
     "A dict of counts. most_common(n), subtract, and + combine histograms. Handy for frequencies and bag-of-words. Values can go negative after subtract.",
     ["Count dict.", "most_common.", "Adds like bags."], "collections"),
    ("defaultdict", "What is defaultdict?",
     "A dict that calls a factory for missing keys (list, int, set). d[k].append(x) never KeyErrors. Do not use it when missing should be an error — that hides bugs.",
     ["Factory for missing keys.", "list/int/set factories.", "Not when missing is a bug."], "collections"),
    ("deque", "When is a deque better than a list?",
     "O(1) appends and pops on both ends. A list is O(n) at the left. Use deque for queues and sliding windows. It is not for random indexing of a huge buffer.",
     ["O(1) both ends.", "List pop(0) is O(n).", "Queues and windows."], "collections"),
    ("heapq", "What is heapq for?",
     "A binary heap in a plain list. heappush/heappop give a min-heap. Use nsmallest/nlargest for top-k. There is no max-heap type — negate numbers or wrap in tuples.",
     ["Min-heap on a list.", "Top-k with nlargest.", "Negate for max-heap."], "collections"),
    ("walrus", "What is the walrus operator?",
     ":= assigns inside an expression: while (line := f.readline()). Use it to avoid computing twice. Do not nest it into unreadable conditions.",
     ["Assign in an expression.", "Avoid double work.", "Keep it readable."], "syntax"),
    ("match-case", "What is match/case?",
     "Structural pattern matching (3.10+). It can match literals, sequences, mappings, and class patterns. Use a discriminant field like OOP switch, and a catch-all case _.",
     ["Pattern matching.", "Class and sequence patterns.", "case _ is the default."], "syntax"),
    ("str-repr", "What is the difference between __str__ and __repr__?",
     "__str__ is for users (print). __repr__ is for developers (debug, the REPL) and should be unambiguous, ideally round-trippable. If you only define one, define __repr__.",
     ["str is user-facing.", "repr is for debug.", "Prefer defining __repr__."], "data-model"),
    ("name-mangling", "What is name mangling?",
     "Attributes starting with __ but not ending with __ are renamed to _ClassName__attr. It is not true privacy — it avoids subclass clashes. Use a single underscore for \"internal\".",
     ["__foo becomes _Class__foo.", "Not real privacy.", "Single _ for internal."], "oop"),
    ("abc", "What is an ABC?",
     "An abstract base class (abc.ABC) that can declare @abstractmethod. Instantiating a subclass that skipped those methods fails. Use ABCs for virtual subclasses and isinstance checks.",
     ["Abstract methods.", "Cannot instantiate incomplete subclasses.", "isinstance works."], "oop"),
    ("protocol", "What is typing.Protocol versus an ABC?",
     "Protocol is structural: if the methods exist, the type matches (optionally @runtime_checkable). ABC is nominal: you inherit or register. Prefer Protocol for duck-typed libraries.",
     ["Protocol is structural.", "ABC is nominal.", "runtime_checkable for isinstance."], "typing"),
    ("overload", "What is typing.overload?",
     "Stacked @overload signatures document different call shapes; the implementation is a single function. They exist only for the type checker — at runtime only the implementation remains.",
     ["Multiple signatures.", "One runtime function.", "Type-checker only."], "typing"),
    ("circular-import", "How do you break a circular import?",
     "Move the shared type to a third module, import inside the function that needs it, or use TYPE_CHECKING for type-only imports. Cycles are a design smell — flatten the graph.",
     ["Third module.", "Import inside the function.", "TYPE_CHECKING for types."], "packaging"),
    ("all", "What is __all__?",
     "A list of public names for from module import *. It does not enforce privacy. Use it to keep * imports from leaking internals; explicit imports are still better.",
     ["Public names for import *.", "Not real privacy.", "Prefer explicit imports."], "packaging"),
    ("pickle-json", "When do you use pickle versus json?",
     "json is text, interoperable, and safe for untrusted data if you do not use a custom decoder that executes code. pickle serializes arbitrary Python objects and can run code on load — never unpickle untrusted bytes.",
     ["json is safe and portable.", "pickle is Python-only.", "Never unpickle untrusted data."], "stdlib"),
    ("literal-eval", "What is ast.literal_eval versus eval?",
     "eval runs any Python expression — a security hole. ast.literal_eval only accepts literals (dicts, lists, numbers, strings). Use it for slightly richer config than json.",
     ["eval executes code.", "literal_eval is literals only.", "Use it instead of eval."], "stdlib"),
    ("gil-313", "What changed about the GIL in Python 3.13?",
     "3.13 ships an experimental free-threaded (no-GIL) build per PEP 703. Default CPython still has the GIL. Mention it, then say you still write I/O threads vs multiprocessing for CPU on today's default build.",
     ["Experimental no-GIL build.", "Default still has the GIL.", "Same I/O vs CPU advice."], "concurrency"),
    ("thread-process-async", "When do you choose threading, multiprocessing, or asyncio?",
     "I/O-bound many waits: asyncio or threads (GIL released on I/O). CPU-bound Python: multiprocessing or a native library. Mixing: run blocking work in a thread pool from asyncio (to_thread).",
     ["I/O: asyncio or threads.", "CPU: processes.", "to_thread for blocking calls."], "concurrency"),
    ("futures", "What is concurrent.futures?",
     "A high-level pool API: ThreadPoolExecutor and ProcessPoolExecutor with submit/map. Prefer it over raw Thread/Process when you just need N workers and futures.",
     ["Thread and process pools.", "submit and map.", "Better than raw Thread()."], "concurrency"),
    ("deadlock", "What is a deadlock?",
     "Two or more waiters each hold a lock the other needs. Avoid by lock ordering, using a timeout, or not holding two locks. RLock does not fix a lock-order deadlock between two objects.",
     ["Circular lock wait.", "Lock ordering.", "Timeouts."], "concurrency"),
    ("rlock", "What is the difference between Lock and RLock?",
     "Lock cannot be acquired twice by the same thread — that deadlocks yourself. RLock is reentrant: the owner can acquire again. Use RLock for callbacks into code that already holds the lock.",
     ["Lock is not reentrant.", "RLock can nest.", "Callbacks need RLock."], "concurrency"),
    ("asyncio-sleep", "Why is time.sleep a bug inside asyncio?",
     "time.sleep blocks the entire event loop, so every task stalls. Use await asyncio.sleep. Same class of bug as requests.get in async def — use httpx/aiohttp.",
     ["Blocks the event loop.", "Use asyncio.sleep.", "Same as sync requests."], "concurrency"),
    ("gather", "What is the difference between asyncio.gather and create_task?",
     "create_task schedules one coroutine. gather waits on many and collects results (or raises). Tasks start when created; gather also starts them. Use TaskGroup (3.11+) for structured shutdown.",
     ["create_task starts one.", "gather waits on many.", "TaskGroup is structured."], "concurrency"),
    ("call", "What does __call__ do?",
     "It makes instances callable: obj() runs obj.__call__. Use it for function-like objects that hold state (a tokenizer, a metric). Classes are already callable via type.__call__.",
     ["Instances become functions.", "Stateful callables.", "obj() → __call__."], "oop"),
    ("getitem", "What is __getitem__?",
     "It implements obj[key] — sequences, mappings, and numpy-style slices. Pair with __len__ and __iter__ for a complete container. Missing keys should raise IndexError or KeyError, not return None.",
     ["obj[key].", "Raise KeyError/IndexError.", "With __len__/__iter__."], "oop"),
    ("memoryview", "What is a memoryview?",
     "A zero-copy window onto bytes-like data. You can slice without copying. Use it when parsing binary buffers so you do not allocate a new bytes for every field.",
     ["Zero-copy slice of bytes.", "No extra allocation.", "Binary parsers."], "memory"),
    ("pathlib", "When do you use pathlib instead of os.path?",
     "Path objects compose with / , have .read_text(), .glob(), and .exists(). os.path is stringly. New code should use pathlib unless an API demands strings.",
     ["Path / \"file\".", "read_text, glob.", "Prefer it in new code."], "stdlib"),
    ("subprocess", "Why prefer subprocess over os.system?",
     "subprocess can avoid the shell (shell=False), capture stdout/stderr, and raise on non-zero (check=True). os.system is a shell string — injection risk and no capture.",
     ["No shell by default.", "Capture streams.", "os.system is injection-prone."], "stdlib"),
    ("logging", "Why use logging instead of print?",
     "Levels, loggers per module, handlers (file, stderr), and runtime config. print cannot be filtered in production. Logger names follow the package tree.",
     ["Levels and handlers.", "Per-module loggers.", "print cannot be filtered."], "stdlib"),
    ("gil-numpy", "Does NumPy care about the GIL?",
     "Many NumPy (and pandas) C loops release the GIL, so threads can parallelize that C work. Pure Python loops around NumPy still serialize. Profile before you add processes.",
     ["C loops can release the GIL.", "Python loops still serialize.", "Measure first."], "concurrency"),
    ("comprehension-scope", "Do list comprehensions leak the loop variable?",
     "In Python 3, no — the loop name is local to the comprehension. In Python 2 it leaked. Generator expressions were always scoped. Do not rely on the loop var after the comprehension.",
     ["Py3: local to the comprehension.", "Py2 leaked.", "Do not use the name after."], "syntax"),
    ("sort-key", "How do you sort with a key function?",
     "list.sort(key=...) or sorted(..., key=...). The key is computed once per item (Decorate-Sort-Undecorate). For reverse+stable, sort twice from the last key to the first.",
     ["key= is computed once.", "sorted returns a new list.", "sort is in-place."], "collections"),
    ("stable-sort", "Is Python's sort stable?",
     "Yes, Timsort is stable: equal keys keep original order. That is why you can sort by last name then first name with two passes, least-significant first.",
     ["Timsort is stable.", "Equal keys keep order.", "Multi-key: sort last key first."], "collections"),
    ("zip", "What does zip do, and what happens with unequal lengths?",
     "zip pairs items until the shortest iterable ends. Use itertools.zip_longest for padding. In 3.10+, zip(..., strict=True) errors on length mismatch.",
     ["Stops at the shortest.", "zip_longest pads.", "strict=True errors."], "stdlib"),
    ("enumerate", "Why use enumerate instead of range(len)?",
     "enumerate(xs) yields (index, item) and works on any iterable, not only sequences. range(len) fails on generators and is less readable.",
     ["(index, item).", "Works on any iterable.", "Do not range(len)."], "style"),
    ("with-open", "Why is with open(...) required?",
     "It closes the file on success and on exception. A bare f = open() leaks FDs if you return early. Text mode is the default; pass encoding=\"utf-8\" explicitly.",
     ["Closes on exception.", "Set encoding.", "No leaked FDs."], "stdlib"),
    ("is-none", "Why compare to None with is, not ==?",
     "None is a singleton, so is is correct and faster. A custom __eq__ can make == None true for other objects. linters flag == None.",
     ["None is a singleton.", "__eq__ can lie.", "Use is None."], "style"),
    ("truthiness", "What is considered false in Python?",
     "False, None, 0, 0.0, empty str/list/dict/set, and objects whose __bool__ or __len__ returns 0. A custom class is true by default.",
     ["Empty containers are false.", "0 is false.", "User objects are true by default."], "data-model"),
    ("or-and", "How do and and or return values?",
     "They return the last evaluated operand, not a coerced bool. a or b is a if a is truthy else b. That is why x = s or \"default\" works.",
     ["Return the operand.", "or is the first truthy.", "Used for defaults."], "syntax"),
    ("global", "When do you need the global keyword?",
     "Only to assign to a module-level name inside a function. Reading a global needs no keyword. If you assign without global, Python makes a local and you get UnboundLocalError on earlier reads.",
     ["Needed for assignment.", "Reads are fine.", "UnboundLocalError otherwise."], "data-model"),
    ("nonlocal", "When do you need nonlocal?",
     "To assign to a name in an enclosing (but not global) function. Closures that increment a counter need nonlocal count. Without it you create a local.",
     ["Enclosing function names.", "Counters in closures.", "Not for globals."], "data-model"),
    ("ellipsis", "What is Ellipsis (...) used for?",
     "A singleton. NumPy uses it for slicing. Type stubs use it in protocols and typing. Type checkers accept ... in abstract bodies. It is not a placeholder that runtime-skips.",
     ["A singleton object.", "NumPy slices.", "Stubs and Protocol bodies."], "syntax"),
    ("ellipsis-type", "What does x: tuple[int, ...] mean?",
     "A tuple of ints of unknown length. tuple[int] is a one-int tuple. Homogeneous variadic tuples use the ellipsis.",
     ["Variable-length tuple of int.", "tuple[int] is length 1.", "Homogeneous rest."], "typing"),
    ("typeddict", "What is TypedDict?",
     "A dict with a known set of keys and value types, checked by the type checker. Runtime is still a dict. Use total=False for optional keys. Not a replacement for a dataclass when you want attributes.",
     ["Typed dict keys.", "Runtime dict.", "total=False for optional."], "typing"),
    ("newtype", "What is NewType?",
     "A type-checker-only distinct alias: UserId = NewType(\"UserId\", int). At runtime it is a dummy callable that returns the value. It prevents mixing UserId with raw int in typed code.",
     ["Distinct at type-check time.", "Runtime is still the value.", "Stops mixing IDs."], "typing"),
    ("self-type", "What is typing.Self?",
     "The type of the current class, including subclasses. fluent() -> Self means a subclass method returns that subclass, not the base. Prefer it over quoting the class name.",
     ["Current class type.", "Subclass-preserving fluent APIs.", "Better than hard-coding the name."], "typing"),
    ("paramspec", "What is ParamSpec for?",
     "It captures a callable's parameter list so a decorator can keep the wrapped signature. Concatenate adds extra args. You need it for typed decorators in 3.10+.",
     ["Captures parameters.", "Decorators keep signatures.", "3.10+."], "typing"),
    ("mypy", "What does a type checker like mypy give you?",
     "It verifies annotations without running the code: wrong keys, None, and mismatched returns. It does not prove runtime correctness. Gradual: untyped code is Any unless you forbid it.",
     ["Static check of annotations.", "Not a runtime proof.", "Untyped is Any."], "typing"),
    ("gil-io", "Why can threads still help if the GIL exists?",
     "The GIL is released around many blocking I/O calls (socket, disk, some C APIs). Threads overlap those waits. CPU-bound Python bytecode does not overlap — that is when you use processes.",
     ["GIL released on I/O.", "Threads overlap waits.", "CPU bytecode does not overlap."], "concurrency"),
    ("process-pool-pickle", "What is the multiprocessing pickle gotcha?",
     "Process pools pickle the function and arguments to the child. Lambdas, nested functions, and unpickleable objects fail. Use top-level functions and simple data, or a shared-memory array.",
     ["Args are pickled.", "No lambdas.", "Top-level functions."], "concurrency"),
    ("queue", "When do you use queue.Queue?",
     "A thread-safe FIFO between producer and consumer threads. task_done/join coordinate shutdown. For processes use multiprocessing.Queue. asyncio has asyncio.Queue.",
     ["Thread-safe FIFO.", "task_done/join.", "Different Queue per model."], "concurrency"),
    ("gil-why", "Why does CPython have a GIL?",
     "It keeps reference counting simple and makes C extensions easier to write by serializing bytecode. The cost is no CPU parallelism from threads. That trade was explicit; PEP 703 is the long-term unwind.",
     ["Simple refcount.", "Easier C extensions.", "Cost is thread CPU parallelism."], "concurrency"),
    ("c-api-gil", "How do C extensions deal with the GIL?",
     "They call Py_BEGIN_ALLOW_THREADS around blocking or parallel C work, then Py_END_ALLOW_THREADS. NumPy and zlib do this. If they forget, they hold the GIL and stall other threads.",
     ["Release around C work.", "NumPy does this.", "Holding it stalls threads."], "concurrency"),
    ("bytecode", "What is a .pyc file?",
     "Cached bytecode in __pycache__. Python loads it when the source mtime matches, skipping parse. It is not encryption or a speedup of the algorithm — only import time.",
     ["Cached bytecode.", "Faster imports.", "Not a JIT."], "runtime"),
    ("pycache", "Can you run a program from only .pyc files?",
     "Historically yes for many modules, but it is a poor distribution method. Prefer an interpreter plus source or a freeze tool. Hash-based pyc in 3.7+ changes invalidation.",
     ["Not a distribution format.", "Use freeze or wheels.", "Hash-based pyc exist."], "runtime"),
    ("import-time", "What runs at import time?",
     "The module body: class and def statements build objects, top-level calls run. Heavy work at import slows startup and complicates tests. Keep import graphs lazy.",
     ["The whole module body.", "Keep it light.", "Lazy-import inside functions."], "packaging"),
    ("star-import", "Why is from module import * discouraged?",
     "It dumps names into your namespace, hides origin, breaks linters, and can overwrite names. __all__ limits the damage but explicit imports are the rule.",
     ["Namespace clutter.", "Hides origin.", "Use explicit names."], "style"),
    ("relative-import", "What is a relative import?",
     "from . import sibling or from ..pkg import x. It only works inside a package (not a script run as __main__ from that file). Running python -m pkg.mod is the usual fix.",
     ["Leading dots.", "Package only.", "python -m pkg.mod."], "packaging"),
    ("sys-path", "What is sys.path?",
     "The list of directories import searches. It starts with the script dir, then PYTHONPATH, then site-packages. Mutating it at runtime is a last resort — fix the install.",
     ["Import search list.", "Script dir first.", "Do not hack it in prod."], "packaging"),
    ("ellipsis-slice", "What does seq[::-1] do?",
     "It reverses a sequence by slicing with step -1, returning a new object. For a list it copies. For reversing in place use list.reverse().",
     ["Reverse copy.", "Step -1.", "reverse() is in-place."], "collections"),
    ("slice-copy", "Does xs[:] copy a list?",
     "Yes, a shallow copy of the list. Nested objects are still shared. list(xs) and copy.copy do the same outer copy.",
     ["Shallow copy.", "Nested objects shared.", "list(xs) is the same."], "collections"),
    ("id", "What does id() return?",
     "An integer unique for this object during its lifetime (in CPython, often the address). After the object is gone the id can be reused. Do not persist it.",
     ["Unique while alive.", "CPython: address.", "Can be reused later."], "data-model"),
    ("intern", "What is string interning?",
     "CPython reuses some string objects (identifiers, compile-time literals that look like names). is can then succeed for equal strings. Do not rely on it; use == for text.",
     ["Some strings are reused.", "is can lie.", "Compare strings with ==."], "memory"),
    ("small-int", "What is the small integer cache?",
     "CPython interned -5..256 so those ints are singletons. is works there and fails for 257. Always use == for numbers.",
     ["-5 to 256 cached.", "is fails outside.", "Use ==."], "memory"),
    ("contextlib", "What is contextlib.closing and suppress?",
     "closing(obj) calls obj.close() in exit — for things that are not context managers. suppress(Exception) swallows that exception. Both are small with-helpers.",
     ["closing calls close().", "suppress swallows listed errors.", "Tiny with-helpers."], "stdlib"),
    ("exit-stack", "What is ExitStack?",
     "A context manager that can enter an unknown number of other context managers at runtime and unwind them. Use it when the set of files or locks is dynamic.",
     ["Dynamic number of withs.", "Unwinds all.", "Runtime-variable resources."], "stdlib"),
    ("weakref-cache", "When do you put weakrefs in a cache?",
     "So the cache does not keep objects alive. When the last strong ref dies, the entry can vanish (with a callback). The existing Practice question: assigning a weakref does not keep the object alive.",
     ["Cache without extending lifetime.", "Callback on death.", "No refcount bump."], "memory"),
    ("gil-io-bound-restated", "Your workload is I/O-bound. Why is multiprocessing usually the wrong first tool?",
     "Processes copy memory, cost IPC, and start slowly. I/O already releases the GIL, so threads or asyncio overlap waits with less overhead. Reach for processes when the bottleneck is Python CPU.",
     ["IPC and RAM cost.", "I/O already overlaps with threads.", "Processes for CPU."], "concurrency"),
]

TS: list[tuple] = [
    ("declaration-merging", "What is declaration merging in TypeScript?",
     "Multiple interface (or namespace) declarations with the same name are combined. That is how you augment Express.Request. type aliases do not merge — a second type Foo is an error.",
     ["Interfaces merge.", "Used to augment libraries.", "type aliases do not merge."], "types"),
    ("satisfies", "What does the satisfies operator do?",
     "It checks a value against a type without widening the value's inferred type. as Colors would widen literals to string; satisfies Colors keeps \"blue\" as \"blue\" and still errors on extra/missing keys.",
     ["Checks without widening.", "Keeps literal types.", "Safer than as."], "types"),
    ("as-const", "What does as const do?",
     "It infers the narrowest readonly types: arrays become readonly tuples, fields become literal types. Use it for config objects and const arrays you will use as unions.",
     ["Narrowest readonly types.", "Tuples and literals.", "Config objects."], "types"),
    ("keyof", "What does keyof T produce?",
     "A union of T's property names: keyof {id: number; name: string} is \"id\" | \"name\". Combined with T[K] you write type-safe property helpers: function get<T, K extends keyof T>(o: T, k: K): T[K].",
     ["Union of keys.", "T[K] is the value type.", "Safe property access."], "types"),
    ("typeof-type", "How does typeof work in a type position?",
     "typeof value produces the static type of that value. type Config = typeof config stays in sync with the object. It is not the runtime typeof operator — that one returns a string.",
     ["Type of a value.", "Keeps types in sync.", "Different from runtime typeof."], "types"),
    ("infer", "What does infer do in a conditional type?",
     "It introduces a new type variable in the extends clause: T extends Promise<infer U> ? U : T unwraps a Promise. Built-ins like ReturnType use infer internally.",
     ["Names a piece of a type.", "Promise<infer U> unwraps.", "ReturnType uses it."], "types"),
    ("discriminated-union", "What is a discriminated union?",
     "A union of objects that share a literal field (kind: \"circle\" | \"square\"). switch (x.kind) narrows the rest of the fields. Add a never default so new variants fail at compile time.",
     ["Shared literal tag.", "switch narrows.", "never default for exhaustiveness."], "types"),
    ("never-exhaustive", "How do you make a switch exhaustive with never?",
     "In the default branch, assign the value to never (or call assertNever(x: never)). If a new union member appears, TypeScript errors. That is the senior check on discriminated unions.",
     ["Default is never.", "New variants fail the build.", "assertNever helper."], "types"),
    ("branded", "What is a branded type?",
     "A nominal-ish type: type UserId = string & { readonly __brand: \"UserId\" }. You cannot pass a raw string without a constructor. Use it so UserId and OrderId are not interchangeable.",
     ["string & { __brand }.", "Stops mixing IDs.", "Needs a constructor helper."], "types"),
    ("structural", "What is structural typing?",
     "Compatibility is by shape, not by name. If it has the required fields, it is assignable. That is why extra fields on an object literal can error (excess property check) while a variable with extra fields may still assign.",
     ["Shape, not name.", "Duck typing at compile time.", "Excess property checks on literals."], "types"),
    ("excess-property", "What is an excess property check?",
     "When you pass an object literal to a type, unknown keys are errors. After assigning to a variable, extra keys are allowed (freshness). It catches typos on literals only.",
     ["Literal extra keys error.", "Variables are fresher.", "Typo catcher."], "types"),
    ("partial-pick", "What do Partial, Pick, Omit, and Record do?",
     "Partial<T> makes every field optional. Pick<T, K> keeps keys. Omit<T, K> drops keys. Record<K, V> is a map from keys K to V. They are mapped types in the standard library.",
     ["Partial = optional fields.", "Pick/Omit keys.", "Record is a map type."], "types"),
    ("returntype", "What is ReturnType<T>?",
     "It extracts the return type of a function type. Parameters<T> extracts the args as a tuple. ConstructorParameters and InstanceType do the same for constructors.",
     ["Return type of a function.", "Parameters is the args tuple.", "InstanceType for classes."], "types"),
    ("awaited", "What is Awaited<T>?",
     "It recursively unwraps PromiseLike. Awaited<Promise<Promise<number>>> is number. Use it when a helper must match what await returns.",
     ["Unwraps Promises.", "Recursive.", "Matches await."], "types"),
    ("exclude-extract", "What do Exclude, Extract, and NonNullable do?",
     "Exclude<T, U> removes from T anything assignable to U. Extract keeps those. NonNullable removes null | undefined. They operate on unions.",
     ["Exclude removes.", "Extract keeps.", "NonNullable drops nullish."], "types"),
    ("this-param", "What is a this parameter on a function?",
     "The first fake parameter named this: function f(this: HTMLElement, ev: Event). It types this inside the function and is erased at emit. Call it as a method or with .call.",
     ["Fake first parameter.", "Types this.", "Erased at emit."], "functions"),
    ("overloads", "How do function overloads work in TypeScript?",
     "You write two or more signatures, then one implementation whose params are the union. Callers see the overloads, not the implementation. Order matters: more specific first.",
     ["Several signatures, one body.", "Specific first.", "Callers see overloads."], "functions"),
    ("readonly-vs-const", "What is the difference between readonly and const?",
     "const prevents rebinding a variable; the object's fields may still mutate. readonly on a property or readonly T[] prevents writes through that type. Use both: const x: readonly number[] = [1].",
     ["const is the binding.", "readonly is the property.", "Arrays need readonly T[]."], "types"),
    ("tuple-vs-array", "How do tuples differ from arrays in TypeScript?",
     "A tuple has a fixed length and per-index types: [string, number]. Arrays are number[]. labeled tuples and rest tuples exist. as const on an array often produces a readonly tuple.",
     ["Fixed length, per-index types.", "label: [x: number, y: number].", "as const makes a tuple."], "types"),
    ("rest-tuple", "What is a rest element in a tuple?",
     "[string, ...number[]] is a string followed by any number of numbers. Variadic tuples let you concatenate tuples in types. They power typed bind/call helpers.",
     ["... in a tuple type.", "Variadic concat.", "Typed bind."], "types"),
    ("const-enum", "What is a const enum?",
     "An enum inlined at compile time — no runtime object unless isolatedModules forbids it. They break if you compile files separately. Prefer union literals or a normal enum.",
     ["Inlined, no runtime object.", "Breaks isolatedModules.", "Prefer string unions."], "types"),
    ("enum-reverse", "What is reverse mapping on numeric enums?",
     "Numeric enums emit an object that maps name → number and number → name. String enums do not reverse-map. That extra object is why many teams avoid numeric enums.",
     ["Numeric enums go both ways.", "String enums do not.", "Runtime object cost."], "types"),
    ("union-vs-enum", "When do you prefer a string union over an enum?",
     "Unions are types-only, tree-shake trivially, and autocomplete well. Enums exist at runtime and have quirks. Use a union unless you need a runtime object or a numeric protocol.",
     ["Unions erase.", "Enums are runtime.", "Unions for most APIs."], "types"),
    ("hash-private", "What is the difference between private and #private?",
     "private is TypeScript-only and erased — runtime still accessible. #field is JS hard privacy (syntax error outside the class). Use # when privacy must hold at runtime.",
     ["private is compile-time.", "# is runtime privacy.", "Use # for real hiding."], "classes"),
    ("abstract-class", "What is an abstract class in TypeScript?",
     "A class you cannot new, with optional abstract methods subclasses must implement. Unlike an interface it can have implementations and runtime instanceof. Prefer an interface when there is no shared code.",
     ["Cannot construct.", "Can have method bodies.", "Interface if no code to share."], "classes"),
    ("implements", "What does implements do?",
     "It asks the class to satisfy an interface or type. It does not change emit. Missing fields are errors. implements does not pull in default methods — that is extends.",
     ["Checks the shape.", "No runtime mixins.", "extends for code reuse."], "classes"),
    ("definite-assignment", "What is definite assignment assertion?",
     "x!: number on a field tells TypeScript it will be assigned (by a DI framework) before use. It skips the \"not initialized\" error. Overuse hides uninitialized bugs.",
     ["field!: Type.", "For DI frameworks.", "Can hide bugs."], "classes"),
    ("non-null", "What does the non-null assertion operator do?",
     "value! says this is not null or undefined. It is an assertion, not a check. Prefer narrowing. Use it when you just checked and the checker cannot see it.",
     ["Asserts not null.", "No runtime check.", "Prefer real narrowing."], "types"),
    ("optional-chaining", "What is optional chaining versus &&?",
     "a?.b short-circuits on null or undefined and types the result as T | undefined. a && a.b also short-circuits on \"\" and 0. Use ?. for nullish, not for all falsy.",
     ["?. is nullish.", "&& is any falsy.", "Prefer ?."], "syntax"),
    ("nullish", "What is ?? versus ||?",
     "?? is null or undefined only. || treats 0, \"\", and false as missing. Use ?? for defaults of numbers and strings that can be empty.",
     ["?? is nullish.", "|| is any falsy.", "0 should use ??."], "syntax"),
    ("in-narrow", "How does the in operator narrow types?",
     "if (\"x\" in obj) narrows a union to members that have x. It is a type guard for object unions without a discriminant. Combine with typeof for primitives.",
     ["\"key\" in obj.", "Narrows unions.", "No discriminant needed."], "types"),
    ("type-predicate", "What is a user-defined type predicate?",
     "function isUser(x: unknown): x is User. A true return narrows x to User. The body must actually check; TypeScript trusts the annotation. Use it on Array.filter to keep types.",
     ["x is User.", "Narrows on true.", "filter keeps the type."], "types"),
    ("asserts", "What are assertion functions?",
     "function assert(x: unknown): asserts x is string throws if the check fails and narrows afterward. They model Node's assert. After the call, x is string.",
     ["asserts x is T.", "Throws on failure.", "Narrows after the call."], "types"),
    ("unique-symbol", "What is unique symbol?",
     "A type of a specific symbol: const k: unique symbol = Symbol(). Only that binding has the type. Used for branded keys and well-known protocol fields.",
     ["One specific symbol type.", "Branded keys.", "const k: unique symbol."], "types"),
    ("recursive-type", "How do you write a recursive type?",
     "A type that refers to itself: type Json = string | number | boolean | null | Json[] | { [k: string]: Json }. TypeScript allows this when the recursion is through an object or array.",
     ["Type names itself.", "JSON is the classic.", "Recurse through objects/arrays."], "types"),
    ("distributive", "What is a distributive conditional type?",
     "Naked T extends U ? X : Y distributes over a union T. So NonNullable is implemented that way. Wrap in [T] to disable distribution when you want to test the whole union.",
     ["Naked T distributes.", "Unions split.", "[T] turns it off."], "types"),
    ("key-remap", "What is key remapping in mapped types?",
     "as in { [K in keyof T as `get${Capitalize<K>}`]: () => T[K] }. You can prefix, filter (as never drops a key), and rename keys in one mapped type.",
     ["as in a mapped type.", "Prefix and filter keys.", "as never drops."], "types"),
    ("minus-readonly", "How do you remove readonly in a mapped type?",
     "{-readonly [K in keyof T]: T[K]}. The - modifier undoes readonly or ?. { [K in keyof T]-?: T[K] } makes fields required. That is how Required<T> is built.",
     ["-readonly.", "-? makes required.", "Required uses it."], "types"),
    ("variance", "What is function parameter variance in TypeScript?",
     "With strictFunctionTypes, function parameters are checked contravariantly for function types (not methods). A (x: Animal) => void is not a (x: Dog) => void. Methods stay bivariant for practical DOM APIs.",
     ["strictFunctionTypes.", "Parameters contravariant.", "Methods still bivariant."], "types"),
    ("strict-flags", "What does \"strict\": true turn on?",
     "A bundle: strictNullChecks, noImplicitAny, strictFunctionTypes, strictBindCallApply, strictPropertyInitialization, alwaysStrict, useUnknownInCatchVariables (version-dependent). Turn it on; do not pick flags one by one unless migrating.",
     ["A bundle of checks.", "null, any, this.", "On by default for new apps."], "tooling"),
    ("no-unchecked-index", "What does noUncheckedIndexedAccess do?",
     "obj[key] and arr[i] include undefined because the key might be missing. It catches real holes. You then use ? or a guard. Painful on maps, worth it on arrays.",
     ["Index access is T | undefined.", "Catches holes.", "Guards or ?."], "tooling"),
    ("import-type", "What is import type?",
     "import type { Foo } from \"./foo\" is erased and cannot be used as a value. It avoids circular runtime imports and works with verbatimModuleSyntax and isolatedModules.",
     ["Type-only import.", "Erased.", "Needed with isolatedModules."], "tooling"),
    ("verbatim-module", "What is verbatimModuleSyntax?",
     "Emit imports as you wrote them. You must import type for types and import for values. It matches bundlers and isolatedModules. Mixing type+value in one import needs import { type Foo, bar }.",
     ["Emit what you wrote.", "import type for types.", "Bundler-friendly."], "tooling"),
    ("module-resolution", "What is moduleResolution: bundler?",
     "A resolution mode for Vite/webpack: extension rewriting, package.json exports, and TS path mapping the way bundlers do. node10 is legacy. Use bundler for frontend, Node16/NodeNext for Node ESM.",
     ["Matches Vite/webpack.", "Not node10.", "NodeNext for Node ESM."], "tooling"),
    ("isolated-modules", "Why does isolatedModules matter?",
     "Each file must compile alone (babel/swc/esbuild). That forbids const enum and some re-export type patterns unless you use import type. Turn it on if you are not using tsc as the emitter.",
     ["Per-file transpile.", "No const enum.", "On for babel/swc."], "tooling"),
    ("skip-lib-check", "What does skipLibCheck do?",
     "Skip type-checking .d.ts in node_modules. It speeds builds and avoids errors in other people's types. You still check your code. Almost every app sets it true.",
     ["Skip node_modules .d.ts.", "Faster builds.", "Your code still checked."], "tooling"),
    ("path-alias", "How do path aliases work in TypeScript?",
     "compilerOptions.paths maps \"@app/*\" to src/*. The type checker understands them; the runtime/bundler must too (vite resolve.alias, tsconfig-paths). Aliases are not automatic at runtime in Node.",
     ["paths in tsconfig.", "Bundler must match.", "Not magic in Node."], "tooling"),
    ("esmoduleinterop", "What is esModuleInterop?",
     "It emits helpers so import fs from \"fs\" works with CJS modules that have no default. allowSyntheticDefaultImports only affects checking. Turn esModuleInterop on for Node CJS interop.",
     ["Default import from CJS.", "Emits helpers.", "On for Node."], "tooling"),
    ("jsx", "What does the jsx compiler option change?",
     "react emits React.createElement, react-jsx the automatic runtime, preserve keeps JSX for a later tool, react-native similar to preserve. Vite usually wants preserve or react-jsx depending on the plugin.",
     ["react vs react-jsx.", "preserve for bundlers.", "Does not type-check JSX by itself — jsxImportSource does."], "tooling"),
    ("react-node", "What is the difference between React.ReactNode and React.ReactElement?",
     "ReactElement is a JSX element object. ReactNode is what components may return: element, string, number, null, fragments, arrays. Props children should be ReactNode, not ReactElement.",
     ["ReactElement is JSX object.", "ReactNode includes string/null.", "children: ReactNode."], "react"),
    ("tsc-swc", "When do you use tsc versus swc/esbuild?",
     "tsc is the source of truth for types. swc/esbuild emit JS fast and skip deep checking. Typical app: tsc --noEmit in CI, bundler emits. Libraries that ship .d.ts still need tsc.",
     ["tsc for types.", "swc for emit speed.", "Libraries need tsc for .d.ts."], "tooling"),
    ("project-references", "What are project references?",
     "composite projects that tsc builds in order. A UI package depends on a types package with \"references\". Incremental and enforces boundaries. Needs composite: true and declaration.",
     ["Build graph of tsconfigs.", "composite + declaration.", "Monorepo boundaries."], "tooling"),
    ("using-disposable", "What is using / Disposable in TypeScript?",
     "Explicit Resource Management: using x = getHandle() calls [Symbol.dispose] at block end, like Python with. await using for async dispose. Needs a runtime that implements the symbols.",
     ["like with.", "Symbol.dispose.", "await using for async."], "syntax"),
    ("const-type-params", "What are const type parameters?",
     "function f<const T>(x: T) infers T as the literal type of the argument, like as const on that parameter. Added in TS 5.0. Use it so keys: [\"a\",\"b\"] stays \"a\" | \"b\", not string[].",
     ["const T infers literals.", "TS 5.0.", "Keeps tuple keys."], "types"),
    ("zod-unknown", "How do you type unknown JSON from an API?",
     "Keep it unknown (or a schema). Parse with zod/io-ts/valibot into a typed result. Do not as User the fetch body — that is a lie the compiler cannot check.",
     ["Start as unknown.", "Parse with a schema.", "Do not as User."], "practice"),
    ("module-augmentation-why", "When do you use module augmentation?",
     "To add fields to a library type: declare module \"express\" { interface Request { userId: string } }. It is declaration merging across modules. Keep it in a .d.ts and do not fight the library if a generic would do.",
     ["Extend library types.", "declare module.", "A .d.ts file."], "types"),
    ("d-ts", "What is a .d.ts file?",
     "A declaration file: types without implementations. DefinitelyTyped (@types/foo) is community .d.ts for untyped JS. Your library's tsc emit produces .d.ts next to JS.",
     ["Types only.", "@types on DefinitelyTyped.", "tsc can emit them."], "tooling"),
    ("namespace", "Are namespaces still used?",
     "Rarely. ES modules replaced them. You still see them in old .d.ts and in declaration merging (NodeJS namespace). New code should use import/export.",
     ["Legacy.", "ES modules instead.", "Still in some .d.ts."], "tooling"),
    ("noimplicitany", "What does noImplicitAny catch?",
     "Parameters and values that would otherwise be any without an annotation. It forces you to type public functions. Inside inferred locals you still get inference. Part of strict.",
     ["Unannotated params.", "Forces public types.", "Inferred locals still work."], "tooling"),
    ("strict-null", "What does strictNullChecks change?",
     "null and undefined are not assignable to string. You write string | null and narrow. Most production bugs this flag catches are \"it was undefined.\" Keep it on.",
     ["null is not string.", "Narrow before use.", "On in strict."], "tooling"),
    ("this-in-callback", "How do you type this in a callback that loses the method?",
     "Extract the function and pass a this parameter, or use an arrow so this is lexical. bind returns a function whose this is already bound — types need ThisParameterType or a wrapper. Prefer arrows for React handlers.",
     ["Arrow keeps this.", "this: T on a function.", "bind erases this."], "functions"),
    ("jsx-intrinsic", "How do you type a custom JSX intrinsic element?",
     "Augment JSX.IntrinsicElements in a .d.ts: interface IntrinsicElements { \"my-el\": { foo: string } }. That is how web components get typed in JSX.",
     ["JSX.IntrinsicElements.", "Augment in .d.ts.", "Web components."], "react"),
    ("readonly-tuple", "What is readonly [string, number]?",
     "A tuple you cannot mutate (no push, no index assign). Useful for pairs you pass around. as const often infers this. Distinct from readonly string[].",
     ["Immutable tuple.", "as const infers it.", "Not the same as readonly array."], "types"),
    ("index-signature-union", "Why can't an index signature mix with a required conflicting property easily?",
     "All named properties must be assignable to the index signature. { [k: string]: number; name: string } is an error because string is not a number. Use a union value type or a mapped type.",
     ["Named props ⊆ index type.", "string vs number clash.", "Widen the index type."], "types"),
    ("unknown-json-parse", "What does JSON.parse return, and how should you type it?",
     "any by default in TS's lib, which is unsafe. Prefer a wrapper that returns unknown, then parse. never as the result of parse is a lie.",
     ["lib says any.", "Treat as unknown.", "Then schema-parse."], "practice"),
    ("template-key", "How do template literal types help APIs?",
     "type EventName = `on${Capitalize<string>}` or `get${Capitalize<K>}`. They build string APIs from keys. Combined with mapped remapping you generate getter names from a model.",
     ["Strings as types.", "Prefix keys.", "Generate API names."], "types"),
    ("capitalize", "What do Uppercase, Lowercase, Capitalize, and Uncapitalize do?",
     "Intrinsic string manipulation types. Capitalize<\"foo\"> is \"Foo\". Used with template literals and key remapping. They are compiler intrinsics, not JS calls.",
     ["String literal transforms.", "Capitalize for getters.", "Compile-time only."], "types"),
    ("noinfer", "What is NoInfer<T>?",
     "A helper (TS 5.4) that blocks a type argument from being inferred from that position, so another argument wins inference. Use it so a defaulted generic does not collapse to the default too early.",
     ["Blocks inference there.", "TS 5.4.", "Other args win."], "types"),
    ("exact-optional", "What does exactOptionalPropertyTypes do?",
     "Optional props cannot be explicitly assigned undefined unless the type includes undefined. { x?: string } rejects { x: undefined }. Catches the optional-vs-undefined mix-up.",
     ["No explicit undefined.", "Optional ≠ undefined.", "A strict extra flag."], "tooling"),
    ("use-unknown-catch", "What is useUnknownInCatchVariables?",
     "catch (e) types e as unknown instead of any (on in modern strict). You must narrow before reading e.message. Correct because thrown values need not be Error.",
     ["catch e is unknown.", "Narrow before .message.", "Not always Error."], "tooling"),
    ("satisfies-record", "Why use satisfies Record<string, Handler> on a map of functions?",
     "It checks every value is a Handler but keeps each key's literal type, so you can still do map.foo and autocomplete keys. A type annotation Record<string, Handler> would forget the keys.",
     ["Checks values, keeps keys.", "Better than a Record annotation.", "Autocomplete stays."], "types"),
]


def pack(pid: str, title: str, blurb: str, group: str, group_title: str, rows: list[tuple], prefix: str) -> dict:
    questions = []
    for row in rows:
        key, text, answer, hints, topic = row
        questions.append(item(
            qid=f"{prefix}-{key}",
            pack=pid,
            group=group,
            topic=f"{group}-{topic}",
            title=topic.replace("-", " ").title(),
            text=text,
            answer=answer,
            hints=hints,
        ))
    return {
        "packs": [{
            "id": pid,
            "title": title,
            "blurb": blurb,
            "groups": [{"id": group, "title": group_title}],
            "questions": questions,
        }],
        "positions": [],
    }


def existing_texts(group: str, skip: set[str]) -> set[str]:
    texts = set()
    for path in OUT_DIR.glob("*.json"):
        if path.name in skip:
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        for p in data.get("packs") or []:
            for q in p.get("questions") or []:
                if q.get("groupId") == group:
                    texts.add(" ".join((q.get("text") or "").lower().split()))
    return texts


def drop_dupes(rows: list[tuple], group: str, skip: set[str]) -> list[tuple]:
    seen = existing_texts(group, skip)
    out = []
    for row in rows:
        key = " ".join(row[1].lower().split())
        if key in seen:
            continue
        seen.add(key)
        out.append(row)
    return out


def main() -> None:
    skip = {"python-interview.json", "typescript-interview.json"}
    py_rows = drop_dupes(PYTHON, "python-engineering", skip)
    ts_rows = drop_dupes(TS, "typescript", skip)
    py = pack(
        "python-interview",
        "Python interview",
        "Common Python interview questions researched from public lists (GIL, data model, collections, concurrency).",
        "python-engineering",
        "Python",
        py_rows,
        "py-int",
    )
    ts = pack(
        "typescript-interview",
        "TypeScript interview",
        "Common TypeScript interview questions researched from public lists (types, generics, tsconfig, narrowing).",
        "typescript",
        "TypeScript",
        ts_rows,
        "ts-int",
    )
    (OUT_DIR / "python-interview.json").write_text(json.dumps(py, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (OUT_DIR / "typescript-interview.json").write_text(json.dumps(ts, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"python new={len(py_rows)} typescript new={len(ts_rows)}")


if __name__ == "__main__":
    main()
